/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiV1OverviewTestrackRetrieve } from '../fn/main/api-v-1-overview-testrack-retrieve';
import { ApiV1OverviewTestrackRetrieve$Params } from '../fn/main/api-v-1-overview-testrack-retrieve';
import { apiV1OverviewTestsetRetrieve } from '../fn/main/api-v-1-overview-testset-retrieve';
import { ApiV1OverviewTestsetRetrieve$Params } from '../fn/main/api-v-1-overview-testset-retrieve';

@Injectable({ providedIn: 'root' })
export class MainApiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiV1OverviewTestrackRetrieve()` */
  static readonly ApiV1OverviewTestrackRetrievePath = '/api/v1/overview-testrack';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiV1OverviewTestrackRetrieve()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiV1OverviewTestrackRetrieve$Response(params?: ApiV1OverviewTestrackRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiV1OverviewTestrackRetrieve(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiV1OverviewTestrackRetrieve$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiV1OverviewTestrackRetrieve(params?: ApiV1OverviewTestrackRetrieve$Params, context?: HttpContext): Observable<void> {
    return this.apiV1OverviewTestrackRetrieve$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiV1OverviewTestsetRetrieve()` */
  static readonly ApiV1OverviewTestsetRetrievePath = '/api/v1/overview-testset';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiV1OverviewTestsetRetrieve()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiV1OverviewTestsetRetrieve$Response(params?: ApiV1OverviewTestsetRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiV1OverviewTestsetRetrieve(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiV1OverviewTestsetRetrieve$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiV1OverviewTestsetRetrieve(params?: ApiV1OverviewTestsetRetrieve$Params, context?: HttpContext): Observable<void> {
    return this.apiV1OverviewTestsetRetrieve$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
