/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiV1LogsRetrieve$Params {

/**
 * Filter logs by search term. Uses PostgreSQL full-text search.
 */
  filter?: string;

/**
 * Filter logs by log level. Can be DEBUG, INFO, WARNING, ERROR.
 */
  loglevel?: string;

/**
 * TestRun ID
 */
  testrun_id: number;
}

export function apiV1LogsRetrieve(http: HttpClient, rootUrl: string, params: ApiV1LogsRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiV1LogsRetrieve.PATH, 'get');
  if (params) {
    rb.query('filter', params.filter, {});
    rb.query('loglevel', params.loglevel, {});
    rb.path('testrun_id', params.testrun_id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiV1LogsRetrieve.PATH = '/api/v1/logs/{testrun_id}';
