/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ApiV1BugsShowBugInfoRetrieve$Params {

/**
 * ID of bug for which all information should be shown
 */
  bug_id: number;

/**
 * If true, workitem comments will be queried as well
 */
  comments?: boolean;
}

export function apiV1BugsShowBugInfoRetrieve(http: HttpClient, rootUrl: string, params: ApiV1BugsShowBugInfoRetrieve$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiV1BugsShowBugInfoRetrieve.PATH, 'get');
  if (params) {
    rb.path('bug_id', params.bug_id, {});
    rb.query('comments', params.comments, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiV1BugsShowBugInfoRetrieve.PATH = '/api/v1/bugs/show_bug_info/{bug_id}';
